
CREATE TABLE public.t_ticket
(
    id character varying(32) COLLATE pg_catalog."default" NOT NULL,
    biz_type_id character varying(32) COLLATE pg_catalog."default" NOT NULL,
    evaluation_id character varying(32) COLLATE pg_catalog."default",
    ticket_id character varying(10) COLLATE pg_catalog."default",
    ticket_type character varying(32) COLLATE pg_catalog."default" NOT NULL,
    status smallint NOT NULL,
    tag character varying(2) COLLATE pg_catalog."default",
    types_priority smallint DEFAULT 0,
    priority smallint DEFAULT 0,
    deal_win character varying(32) COLLATE pg_catalog."default",
    transfer_win character varying(32) COLLATE pg_catalog."default",
    deal_user character varying(20) COLLATE pg_catalog."default",
    book_id character varying(32) COLLATE pg_catalog."default",
    call_language character varying(6) COLLATE pg_catalog."default",
    interrupt_long smallint DEFAULT 0,
    previous_book smallint,
    default_eval smallint DEFAULT 0,
    beizhu character varying(200) COLLATE pg_catalog."default",
    mark smallint,
    id_card_info_id character varying(32) COLLATE pg_catalog."default",
    ticket_ser smallint,
    ticket_user character varying(255) COLLATE pg_catalog."default",
    eval_time timestamp(6) without time zone,
    ticket_time timestamp(6) without time zone,
    finish_time timestamp(6) without time zone,
    call_time timestamp(6) without time zone,
    start_time timestamp(6) without time zone,
    call_type character varying(255) COLLATE pg_catalog."default" DEFAULT 1,
    branch_id character varying(32) COLLATE pg_catalog."default" DEFAULT 1,
    id_card_name character varying(100) COLLATE pg_catalog."default",
    extend1 character varying(100) COLLATE pg_catalog."default",
    extend2 character varying(100) COLLATE pg_catalog."default",
    extend3 character varying(100) COLLATE pg_catalog."default",
    extend4 character varying(100) COLLATE pg_catalog."default",
    extend5 character varying(100) COLLATE pg_catalog."default",
    extend6 character varying(100) COLLATE pg_catalog."default",
    extend7 character varying(100) COLLATE pg_catalog."default",
    db_id  character varying(40) not null references agence(id) ON DELETE CASCADE
);